/vtol_gps_mission_node:
  ros__parameters:
    # 좌표 형식: [위도(deg), 경도(deg), 이륙점 기준 고도(m)]
    
    # 1. 이륙 및 대기 (WP1 - Home)
    wp1: [35.06898, 128.0863, 20.0]
    
    # 2. 천이 포인트 (WP2)
    wp2: [35.06861, 128.0868, 20.0]
    
    # 3. 고정익 선회 포인트 1 (WP3)
    wp3: [35.06737, 128.0873, 20.0]
    
    # 4. 고정익 선회 포인트 2 (WP4)
    wp4: [35.06854, 128.0884, 20.0]
    
    # 5. 조난자 발견 및 구조 위치 (Rescue Location) - 고도 5m
    rescue_loc: [35.06945, 128.0864, 5.0]
    
    # 6. 조난자 하기(Drop) 위치 (Drop Location) - 고도 5m [새로 추가됨]
    drop_loc: [35.06883, 128.0858, 5.0]
